default_job = "clippy"

[jobs.clippy]
command = [
  "cargo",
  "clippy",
  "--all-features",
  "--color",
  "always",
]
need_stdout = false

[jobs.test]
command = [
  "cargo",
  "test",
  "--color",
  "always",
  "--",
  "--color",
  "always",
]
need_stdout = true

[keybindings]
t = "job:test"
