---
services:
  oxitraffic:
    container_name: oxitraffic
    image: docker.io/mo8it/oxitraffic:latest
    restart: unless-stopped
    volumes:
      # You can change the source to point to your configuration file.
      - ./config.toml:/volumes/config.toml:Z,ro
    # You can replace the ports section with an internal network for a reverse proxy (like Traefik).
    ports:
      # You can change the source port from 8080.
      - 8080:80
